name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          # Installe les dépendances si un fichier requirements.txt existe
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8

      - name: Vérifier la compilation (syntax check)
        run: python -m compileall .

      - name: Vérifier que les modules se chargent correctement
        run: |
          for module in order portfolio notification stockdata tradezero; do
            echo "Test d'import du module $module..."
            python -c "import ${module}"
          done

      - name: Linting du code avec Flake8
        run: flake8 .

      - name: Exécuter les tests (si des tests existent)
        run: |
          if [ -d tests ]; then
            pip install pytest && pytest;
          else
            echo "Aucun dossier 'tests' trouvé, les tests ne sont pas exécutés.";
          fi
